### ISSUE TITLE
gatttool insufficient encryption

### ISSUE THREAD

**Issue by drink1** [Mic92/hue-ble-ctl#2]
Hello everyone,
I can't make the project work. I have done countless resets of the Phlips Hue lamp, but still: I always get the error "Could not read characteristic".
The BLE protocol says that there is an "insufficient encryption". 
--> The underlying error could be gatttool: How can I get an encrypted connection to the Philips hue lamp with gatttool? I tried all three security levels (low, medium, high) but nothing works. 
Thanks for your help!

**Comment by Mic92** [comment]
I had the same issue on iOS/watchOS. The issue there is that I could not get the bonding to work. After bonding is set up, you no longer get `insufficient encryption`. I think the bonding process can be initiated after turned the lamp on.

**Comment by drink1** [comment]
Perfect! It worked when I first paired the hue lamp with `bluetoothctl` after turning on the lamp. Then `gatttool` and your script work fine.
